-- Create

-- DROP TABLE public.dummy_tree;

CREATE TABLE public.dummy_tree
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(256) COLLATE pg_catalog."default" NOT NULL,
    parent_id bigint,
    tree_child_count bigint NOT NULL DEFAULT 0,
    tree_descendant_count bigint NOT NULL DEFAULT 0,
    tree_level bigint NOT NULL DEFAULT 0,
    tree_path character varying(900) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    tree_position integer NOT NULL DEFAULT 0,
    tree_sort character varying(900) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    CONSTRAINT pk_dummy_tree PRIMARY KEY (id),
    CONSTRAINT fk_dummy_tree_dummy_tree_parent_id FOREIGN KEY (parent_id)
        REFERENCES public.dummy_tree (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.dummy_tree
    OWNER to makc;
-- Index: ix_dummy_tree_name

-- DROP INDEX public.ix_dummy_tree_name;

CREATE INDEX ix_dummy_tree_name
    ON public.dummy_tree USING btree
    (name COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: ix_dummy_tree_parent_id

-- DROP INDEX public.ix_dummy_tree_parent_id;

CREATE INDEX ix_dummy_tree_parent_id
    ON public.dummy_tree USING btree
    (parent_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: ix_dummy_tree_tree_sort

-- DROP INDEX public.ix_dummy_tree_tree_sort;

CREATE INDEX ix_dummy_tree_tree_sort
    ON public.dummy_tree USING btree
    (tree_sort COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

-----------------------------------------------

-- DROP TABLE public.dummy_tree_link;

CREATE TABLE public.dummy_tree_link
(
    id bigint NOT NULL,
    parent_id bigint NOT NULL,
    CONSTRAINT pk_dummy_tree_link PRIMARY KEY (id, parent_id),
    CONSTRAINT fk_dummy_tree_link_dummy_tree FOREIGN KEY (id)
        REFERENCES public.dummy_tree (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.dummy_tree_link
    OWNER to makc;
